### ISSUE TITLE
Fixtures with testing

### ISSUE THREAD

**Issue by jasper502** [stefankroes/ancestry#325]
I am using Minitest to test some Pundit policies etc.  In my case to ensure a record with children is not destroyed.  So I have some category fixtures:

```
parent:
  id: 99
  name: 'Parent'
  ancestry: nil

child:
  id: 100
  name: 'Child'
  ancestry: 99
```

In my tests the parent record always responds TRUE to is_childless? but the child does show that it has a parent:

```
puts categories(:child).ancestry => 99
puts categories(:child).parent.is_childless? => true

```
The issue here is that I set `ancestry: nil` in the parent.  If you skip defining it works ok.  Banged my head against the wall for a while on this and perhaps this should be noted in the README section on testing.

**Comment by kbrock** [comment]
Confused why parent.ancestry = nil would cause the problem.

Did you try it with a string in the child?

```yaml
child:
  id: 100
  name: 'Child'
  ancestry: '99'
```

Did you try it with a string in the parent?

```yaml
child:
  id: 99
  name: 'Parent'
  ancestry: ''
```

I had thought that `nil` was a valid (and the preferred) `ancestry` value.

**Comment by jasper502** [comment]
No - I had not thought about trying that.  I will the next chance I get.

**Comment by umar-ahmed** [comment]
Since fixtures support ERB, would it be possible to use that to generate the ancestry column data automatically for fixtures?

**Comment by Apokly** [comment]
Any solution on this ?

**Comment by kbrock** [comment]
@Apokly It have not used fixtures for many years, as I tend to use factories. So my experience is minimal.

There is no automated way to to this.
But you may want to try:

```yaml
grandparent:
  name: 'Gran'
parent:
  name: 'Parent'
  parent_id: <%= Fixtures.identify(:grandparent) %>
child:
#  id: 100
  name: 'Child'
  ancestry_ids: <%= [Fixtures.identify(:grandparent), Fixtures.identify(:parent)] %>
```

The `ancestry_ids` approach will be quicker, but the `parent_id` may be more convenient (if it works)

Let us know what works for you

**Comment by Apokly** [comment]
Thanks for your reply, @kbrock

I finally used `ancestry` column into my fixtures, like `ancestry: (1,2,3)` and it works.
Haven't test parent's solution, would be great if someone could give a try.

**Comment by kbrock** [comment]
think this is all set. please let me know if there are more questions.

**Comment by matpowel** [comment]
Hey all,

None of these options work for Minitest + Rails 6. Fixtures don't take IDs and I don't know what the "Fixtures.identify" thing is. I haven't been able to drill into how to calculate the ID that will be used for another fixture in the same file to be able to reference the ID of it in the ancestry column.

<rant>
Minitest is now idiomatic in Rails so we're doubling down on switching to Minitest for all our projects. It feels way faster and cleaner in the long run than RSpec, even though RSpec is still fairly ubiquitous on the internets. I also hate factories with a passion, they are slow and I think breed bad behavior in tests.
</rant>

Anyway, I think it would be awesome if there was fixture support for ancestry, I wonder how hard it would be to add support for being able to very easily refer to other fixtures for the "ancestry" column for a model which has_ancestry?

Matt

**Comment by kbrock** [comment]
Hello @matpowel 

Maybe this will help? https://apidock.com/rails/v6.0.0/ActiveRecord/FixtureSet/identify/class

Minitest sure is great. I've supported gems with both minitest and rspec.

With ancestry, I'm still not comfortable with the organization of these specs. I'm not ready to rewrite all the specs. For the time I can devote to ancestry, I'd rather focus on features and PRs.

Best of luck and please share if you have some tips to help other developers who are using ancestry from a minitest project.

**Comment by matpowel** [comment]
Hey @kbrock 

Absolutely I wouldn't expect you to re-write the tests for this project in Minitest, I was just making the case that it would be great to support the idiomatic Rails fixtures style out of the box. The goal is to be able to create an ancestry tree easily in fixtures like this:

```
accounts_payable:
  name: Accounts Payable

bill:
  name: Vendor Invoices
  ancestry: accounts_payable

statement:
  name: Vendor Statements
  ancestry: accounts_payable

tax:
  name: Tax
```

For some reason I couldn't access the Fixtures class in my tests when I tried but I'm sure it's just a require away, so thanks for pointing at that! I'll let you know how it goes.

Matt

**Comment by matpowel** [comment]
Hey this worked (Rails 6.0.3.2, Ruby 2.7.1, Minitest 5.14.1):

```
accounts_payable:
  name: Accounts Payable

bill:
  name: Vendor Invoices
  ancestry: <%= ActiveRecord::FixtureSet.identify(:accounts_payable) %>

statement:
  name: Vendor Statements
  ancestry: <%= ActiveRecord::FixtureSet.identify(:accounts_payable) %>

tax:
  name: Tax
```
