### ISSUE TITLE
i18n locale

### ISSUE THREAD

**Issue by mechnicov** [stefankroes/ancestry#436]
How can I add [this message](https://github.com/stefankroes/ancestry/blob/master/lib/ancestry/instance_methods.rb#L8) to my locale?

**Comment by guilhermedallanol** [comment]
@mechnicov in the model you added `has_ancestry`, overwrite `#ancestry_exclude_self` with something like:
```
  def ancestry_exclude_self
    errors.add(
      :base, :ancestry_exclude_self, resource: self.class.name.humanize
    ) if ancestor_ids.include?(self.id)
  end
```

And in your locale:

```
en:
  activerecord:
    errors:
      models:
        product_category:
          attributes:
            base:
              ancestry_exclude_self: "%{resource} cannot be a descendant of itself."

```
